export const testingPackages = [
  "jest",
  "mocha",
  "chai",
  "junit",
  "pytest",
  "phpunit",
  "cargo-test",
  "NUnit",
  "xUnit",
  "MSTest",
];

export const supportedLanguages = [
  { language: "javascript" },
  { language: "typescript" },
  { language: "python" },
  { language: "java" },
  { language: "c" },
  { language: "cpp" },
  { language: "csharp" },
  { language: "go" },
  { language: "ruby" },
  { language: "php" },
  { language: "swift" },
  { language: "kotlin" },
  { language: "rust" },
  { language: "html" },
  { language: "css" },
  { language: "sass-indented" },
  { language: "scss" },
  { language: "less" },
  { language: "stylus" },
  { language: "handlebars" },
  { language: "javascriptreact" },
  { language: "typescriptreact" },
  { language: "vue" },
];

export const supportedLanguagesExtensions = [
  ".ts",
  ".js",
  ".py",
  ".java",
  ".c",
  ".cpp",
  ".cs",
  ".go",
  ".rb",
  ".php",
  ".swift",
  ".kt",
  ".rs",
  ".html",
  ".hbs",
  ".handlebars",
  ".css",
  ".scss",
  ".sass",
  ".less",
  ".styl",
  ".vue",
  ".jsx",
  ".tsx",
];

export const endingActivationCharacters = [
  ".",
  "[",
  "]",
  ":",
  ";",
  "{",
  "}",
  "=",
  "for",
  "=>",
];

export const startingActivationCharacters = [
  "class",
  "def",
  "function",
  "let",
  "const",
  "int",
  "boolean",
  "struct",
  "long",
  "short",
  "float",
  "double",
  "string",
  "new",
];
